### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/MasterThesis#1]
Hinzufügen von GitHub Pages, damit die Thesis bequem im Browser gelesen werden kann.

**Comment by AMatutat** [comment]
hab ja sonst nix zu tun ^^ 
wontfix

**Comment by cagix** [comment]
oi! das wäre super! ... und dann bitte noch ein export nach epub!

**Comment by cagix** [comment]
btw, dein project funktioniert nicht: das ding steht im project "thesis" immer noch unter "open" :)

**Comment by AMatutat** [comment]
> btw, dein project funktioniert nicht: das ding steht im project "thesis" immer noch unter "open" :)

kanns kaum erwartet bis "thesis" unter "closed" steht.....
