### ISSUE TITLE
LevelG

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/MasterThesis#29]
LevelG nimmt den Graphen und die Räume und "legt" das Level aus. 

Praktisch:
- [x] Graphen in Chains aufteilen
- [x] Configuration-Space berechnen 
- [x] calAttachingPoints
- [x] Iterativer Prozess. 
- [x] Türen platzieren

Theoretisch:
- [x]  Konzept aufschreiben
- [x] Umsetzung aufschreiben
    - [x] Chains 
    - [x] calAttachingPoints
- [x] Kontrolle lesen

**Comment by AMatutat** [comment]
Nur noch diese dämlichen Türen <3

**Comment by cagix** [comment]
und die tunnel!

**Comment by AMatutat** [comment]
> und die tunnel!

sieh du mal zu, dass du dich vertunnelst :P

**Comment by AMatutat** [comment]
DA IS DAT DING!!!!!!!!!!!!
