### ISSUE TITLE
fix json

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/MasterThesis#36]
```
gson sollte IMHO eigentlich funktionieren, wenn du // api 'com.google.code.gson:gson:2.8.8' (Zeile 90) einkommentierst und die Klassen, die gespeichert oder geladen werden sollen, bekannt machst: <!-- <extend-configuration-property name="gdx.reflect.include" value="de.pmdungeon.dungeonCreator.dungeonconverter.Room" />-->... (Zeile 12).
```

**Comment by AMatutat** [comment]
Das dämliche libGDX json tool kommt nicht mit verschachtelten Klassen klar.....
Ist ja auch echt selten in Java das Objekte andere Objekte kennen.........

**Comment by cagix** [comment]
> Das dämliche libGDX json tool kommt nicht mit verschachtelten Klassen klar.....
> Ist ja auch echt selten in Java das Objekte andere Objekte kennen.........

naja, verschachtelte klassen sind aber nicht sooo häufig, oder? ich meine, man kann diese form der kapselung doch auch über packages und separate klassen abbilden? (naja, nicht komplett, aber so halbwegs)

**Comment by AMatutat** [comment]
Verschachtelte Klassen sind der falsche Begriff, mein Fehler.

**Comment by cagix** [comment]
> Verschachtelte Klassen sind der falsche Begriff, mein Fehler.
> libGDX scheitert (scheinbar) schon daran so "simple" Dinger wie eine Liste mit Objekten welche wiederum selbst eine Liste mit anderen Objekten haben, richtig einzulesen.

okay. das ist fies. d.h. direkt den stecker ziehen? oder siehst du noch einen workaround?

**Comment by AMatutat** [comment]
> okay. das ist fies. d.h. direkt den stecker ziehen? oder siehst du noch einen workaround?

also wenn du mich aktuell fragst würde ich das HTML-Target gerne mit einem Knüppel bearbeiten :D 
Tobi meinte ja dass ich da ggf. mit Schleifen etc. was machen kann, muss ich mir morgen mal anschauen.

Aber im allgemeinen bin ich aktuell kein Fan vom HTML.

**Comment by AMatutat** [comment]
HTML IST TOT!!!!!!

dann kann ich wieder zu gson zurück
