### ISSUE TITLE
Stand der Technik

### ISSUE THREAD

**Issue by AMatutat** [AMatutat/MasterThesis#4]
Schreiben des "Stand der Technik" Kapitels
*ca 10-15 Seiten* 
- [x] Kapiteleinleitung
- [x] Was ist Rogue-Like 
- [x] Was ist das PM Dungeon, 
- [x] Graphen und Level. (Warum taugt das was, was kann man damit machen)  
- [x] Regeln für  Gutes Leveldesign
- [x] Bewertungskriterien(für Rogue-Likes) 
- [x] Was ist prozedurale Generierung (Was, Wofür, Vor und Nachteile, Anwendung in der Praxis, Beispiel Algorithmen)
- [x] PM-Dungeon Analyse
- [x] Kontrolle lesen

**Comment by AMatutat** [comment]
Frage:

Die Bewertungsmatrix wird Anhand der Regeln aufgestellt. Aktuell wären das folgende Kriterien
- Lösbarkeit (kritsch)
- Balancing
- Driven by game’s mechanics
- Pacing
- Risk and Reward
- Einzigartigkeit
- Effizienz (durch PCG eig gegeben) 

Theoretisch könnte man jeden Punkt auf einer Skala bewerten und dann die Punkte zusammenaddieren (vermutlich bietet es sich dabei an bestimmte Kriterien mehr zu gewichten als andere).

Die Punkte müssen dann aber objektiv bewertet werden (Checkliste oder so + Begründung?)

Hmpf..... Muss denken.....

**Comment by cagix** [comment]
hört sich vernünftig an

**Comment by AMatutat** [comment]
Für jede Regel wurden jetzt Kriterien formuliert, die (mit gewissem Spielraum) festlegen, ob die Regel erfüllt ist und in welchem Maße. 
Die Güte der Level ist dann die Summe aller Kriterien * Lösbarkeit, wobei Lösbarkeit 0 oder 1 sein kann. 

Frage:
- Sind die Kriterien klar verständlich? 
- Ist klar, warum diese Kriterien ausgewählt wurden? (Ergibt sich eigentlich aus den Regeln)
- Ist die Formel klar?

**Comment by cagix** [comment]
ist das ne frage an mich oder an dich selbst? (vergiss nicht, ich kriege jedes mal ne mail ... :)

**Comment by AMatutat** [comment]
> vergiss nicht, ich kriege jedes mal ne mail ... 

Würd mir ja stinken wenn ich du wäre :P 

Ist eigentlich ehr ne Frage an mich aber deine Meinung ist natürlich immer gern gehört.

**Comment by cagix** [comment]
> > vergiss nicht, ich kriege jedes mal ne mail ...
> Würd mir ja stinken wenn ich du wäre :P

schon okay, könnte mich ja unsubscriben. aber die mails werden eh als pseudo-spam vorsortiert, nur vor dem löschen schaue ich einmal am tag kurz drüber. kann ja doch mal was relevantes dabei sein ;)

> Ist eigentlich ehr ne Frage an mich aber deine Meinung ist natürlich immer gern gehört.

gut. 😎
